#cloud-config

packages:
 - strongswan

write_files:
  - path: /etc/strongswan.conf
    permissions: '0600'
    content: ${strongswan}

  - path: /etc/ipsec.conf
    permissions: '0600'
    content: ${ipsec}

  - path: /etc/ipsec.secrets
    permissions: '0600'
    content: ': ECDSA server.pem'

runcmd:
  - bash -c 'until ls -la /etc/ipsec.d/{cacerts/ca,certs/server,private/server}.pem >/dev/null 2>&1; do echo "Not all the cetificates found. Sleep 5 seconds"; sleep 5; done'
  # just because of `write_files` runs before `users` we need to change the owner with this workaround
  - bash -c 'chown strongswan:root /etc/ipsec.d/{cacerts/ca,certs/server,private/server}.pem'
  - bash -c 'chmod 0400 /etc/ipsec.d/{cacerts,certs,private}/*.pem'
  - systemctl restart strongswan
  - systemctl enable strongswan
