#cloud-config
packages:
 - dnscrypt-proxy

write_files:
  - path: /etc/systemd/system/dnscrypt-proxy.service.d/99-capabilities.conf
    permissions: '0644'
    content: |
      [Service]
      AmbientCapabilities=CAP_NET_BIND_SERVICE

  - path: /etc/dnscrypt-proxy/ip-blacklist.txt
    permissions: '0644'
    content: ${jsonencode(vars.ip-blacklist)}

  - path: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    permissions: '0644'
    content: ${jsonencode(vars.dnscrypt_proxy_toml)}

runcmd:
  - aa-enforce usr.sbin.dnscrypt-proxy
  - systemctl daemon-reload
  - systemctl restart dnscrypt-proxy
  - systemctl enable dnscrypt-proxy
