#cloud-config
apt:
  sources:
    wireguard-ubuntu-wireguard-bionic.list:
      source: deb http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic main
      keyid: AE33835F504A1A25

packages:
 - wireguard
 - wireguard-dkms

write_files:
  - path: /etc/wireguard/wg0.conf
    permissions: '0600'
    content: ${jsonencode(vars.wg_conf)}

runcmd:
%{ for index, user in vars.vpn_users ~}
  - bash -c 'sed s~::${user}::~$(echo '${base64encode(vars.private_keys[index])}' | wg pubkey)~ -i /etc/wireguard/wg0.conf'
%{ endfor ~}
  - echo '${base64encode(vars.server_private_key)}' | wg pubkey > /etc/wireguard/.wg-server.pub
  - systemctl restart wg-quick@wg0 ; systemctl enable wg-quick@wg0
